version: '3.8'

services: 
  asr_dev:
    image: "${IMAGE_NAME}"
    env_file:
      - ../docker.env
    build:
      context: ../../
      dockerfile: docker/${GPU}/Dockerfile
      args:
        GPU: ${GPU}
        CUDA_VERSION: 12.2.0
        CUDA_TOOLS: devel  # base or devel (if you need nvcc, etc.)
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - GPU=$GPU
      - JUPYTER_TOKEN=passwd
      # - MODELS_DIR=${MODELS_DIR:-~/Documents/lollms}
    volumes:
      - ../../data:/app/data
      - ../../models:/app/models
      - ../../notebooks:/app/notebooks
    tty: true
    stdin_open: true
    ports: 
      - "0.0.0.0:8888:8888"    # jupyter
      - "0.0.0.0:8787:8787"    # dask
      - "0.0.0.0:37611:37611"  # dask backup
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8888"]
      interval: 10s
      timeout: 5s
      retries: 3
    command: ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--allow-root", "--no-browser"]

